# Generated by Django 4.1.1 on 2022-10-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.AddField(
            model_name='orders',
            name='address1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
